import * as vscode from 'vscode';

const ACE_MANAGED_PATTERNS = [
    'ace-hooks.json',
    'ace.agent.md',
    'ace-learn.agent.md',
    'ace.instructions.md',
    'SKILL.md'
];

export class AceFileDecorationProvider implements vscode.FileDecorationProvider {
    private _onDidChangeFileDecorations = new vscode.EventEmitter<vscode.Uri | vscode.Uri[] | undefined>();
    readonly onDidChangeFileDecorations = this._onDidChangeFileDecorations.event;

    provideFileDecoration(uri: vscode.Uri): vscode.FileDecoration | undefined {
        const fileName = uri.path.split('/').pop() || '';
        if (ACE_MANAGED_PATTERNS.includes(fileName)) {
            // Verify it's in .github/ directory
            const relative = vscode.workspace.asRelativePath(uri);
            if (relative.startsWith('.github/')) {
                return {
                    badge: 'A',
                    tooltip: 'Managed by ACE - auto-generated by extension',
                    color: new vscode.ThemeColor('charts.green')
                };
            }
        }
        return undefined;
    }
}
